lib/puppet/functions/servicenow_reporting_integration/check_report_processor.rb, manifests/init.pp, spec/acceptance/reporting_spec.rb, spec/classes/init_spec.rb, spec/spec_helper_acceptance_local.rb, templates/servicenow_reporting.yaml.epp
This is a better long-term solution and also fixes the underlying bug
with the existing checksum calculation (where the latter failed to pick
up changes in dependencies).
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PIE-308) Use metadata.json version when checking report processor

lib/puppet/util/servicenow.rb, manifests/init.pp, spec/classes/init_spec.rb
This updates the settings function look for the settings file
(servicenow_reporting.yaml) in Puppet[:confdir] as well as updates
init.pp to look in settings::confdir.
=> (PIE-314) Set settings file location via Puppet confdir

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow_spec.rb
This change formats the timestamp slightly better, and moves it to the
back of the short description.
The improved formatting should be the actual time displayed to the user
when the go to the `Reports` screen in the PE Console. This should
allow users searching for a particular report that caused an incident to
`ctrl-f` search the reports screen to find the correct one based on this
improved timestamp.
Moving the stamp tto back of the string allows the user to parse the
important information about severity and target first.
In the console, when the timezone is `UTC`, that value is replaced by
the string `Z`. Since that seems to be the most common time zone name
mapping I did that one manually, but any other time zones will get the
time zone abreviation value that Ruby has directly.
=> (PIE-306) Timestampt Too Verbose

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/support/unit/reports/shared_examples.rb, spec/unit/reports/servicenow_spec.rb
This adds a report_labels function which is used to populate the
incident description with report labels that describe why an incident
was created. We decided to leave out the 'always' trigger as it didn't
seem helpful.
The create_incident? method now uses two helper methods,
event_conditions, and satisfied_conditions which don't change any
functionality or ordering, but allow us to only calculate the satisfied
conditions once so that they can be reused by the report_labels
function.
=> (PIE-311) Fine grain description of the incident creation reason

lib/puppet/reports/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/unit/reports/servicenow/event_spec.rb
The node field tells Servicenow which node an event relates to.
Without it correlation rules and grouping rules won't work very well.
=> (PIE-335) Populate Node Field For Events

.fixtures.yml, metadata.json
inifile:
1.0.0 is the first released version of the module on the Forge. We
also extend the upper bound to 5.0.0 since that is also likely to
contain a breaking change.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PIE-325) Relax version requirements for some dependencies

manifests/event_management.pp, manifests/incident_management.pp, manifests/init.pp, spec/acceptance/reporting/event_spec.rb, spec/acceptance/reporting/incident_spec.rb, spec/acceptance/reporting/misc_spec.rb, spec/classes/event_management_spec.rb, spec/classes/incident_management_spec.rb, spec/support/classes/shared_contexts.rb, spec/support/classes/shared_examples.rb, templates/servicenow_reporting.yaml.epp
The servicenow_reporting_integration::{incident,event}_management
classes will be how users will use the module. If they want event
management, they will declare
servicenow_reporting_integration::event_management. Otherwise, they can
declare the incident_management class. Note that declaring both classes
leads to undefined behavior (and doesn't make sense).
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PIE-349) Split out event + incident management into separate classes

lib/puppet/reports/servicenow.rb, spec/acceptance/reporting/event_spec.rb
Note: When sending the source instance via the event api it is called
event_class. We use the master_used field from the report to indicate
the fqdn of the puppet server the event originated from.
=> (PIE-345) Send the puppet server fqdn in the event Source Instance.

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/shared_examples.rb, spec/unit/reports/servicenow/misc_spec.rb
We remove the 'satisfied conditions' bit because the current
implementation is based off the incident creation conditions,
which are specific to incident management. Upcoming event management
work will add equivalent information to the description in a way that
can be shared by both incident and event management.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PIE-350) Standardize incident + event descriptions

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/acceptance/reporting/incident_spec.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/shared_examples.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/event_spec.rb
This change adds a function to get a human readable summary of the
changes or failures that have occurred in a Puppet run.
Getting the machine readable version to add to Additional Data will
probably be done by a different function.
=> (PIE-343) Add Resource Names To Description

lib/puppet/util/servicenow.rb, manifests/event_management.pp, manifests/init.pp, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/support/unit/reports/shared_examples.rb, spec/unit/reports/servicenow/event_spec.rb, templates/servicenow_reporting.yaml.epp
If an event status is not in one of the statuses returned by the
calculate_event_conditions method, a null status will be sent to
servicenow which creates an error on the servicenow end. This fix adds a
default status for no change statuses that is applied if a changed
status is not found. A test has been added with an absurd severity to
make sure there is no overlap with the other "1" severity statuses.
=> (PIE-358) Events with no changes now send a severity

files/add_ignore_event_ok_rule_data.erb, files/event_data.json, files/ok_rule_simple_filter.json, metadata.json, tasks/add_ignore_ok_events_rule.json, tasks/add_ignore_ok_events_rule.rb
This change adds a task to the module that will add an event rule to
ignore events with a severity level of 'OK'. These events should
simply represent Puppet runs where nothing happened.
If anything like changes or failures happened, those should events
should have a different severity level that can be targeted with
different rules for how to create alerts for them.
=> (PIE-348) Add ignore OK events rule task

lib/puppet/util/servicenow.rb, manifests/event_management.pp, manifests/incident_management.pp, manifests/init.pp, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/event_spec.rb, spec/unit/reports/servicenow/incident_spec.rb, spec/unit/reports/servicenow/misc_spec.rb, templates/servicenow_reporting.yaml.epp
This change allows users to specify a set of facts that should be
included with every incident that is created.
An example of the description this change would generate based on the
following selected facts is below:
`['identity.user', 'ipaddress','memorysize', 'memoryfree', 'os']`
These facts demonstrate what included facts look like for nested facts
queries, top level facts, and complex facts.
```
This incident was created based on the following conditions: intentional_changes. See the PE console for the full report. You can access the PE console at https://inept-fieldwork.delivery.puppetlabs.net.
facts:
identity.user: "root"
ipaddress: "10.16.112.18"
memorysize: "7.80 GiB"
memoryfree: "2.50 GiB"
os: {
"architecture": "amd64",
"distro": {
"codename": "xenial",
"description": "Ubuntu …
```
=> (PIE-335) Add configurable facts to incidents

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/unit/reports/servicenow/event_spec.rb
This adds a method event_additional_information which returns a pretty
printed json hash of all facts under a top level 'facts' key. It will be
simple to add other top level keys to this method such as resources.
Tests for addtional information have been added but will need to made
more generic if the acceptance tests run on something other than
VMpooler.
=> (PIE-344) Add facts to the addtional information field

lib/puppet/util/servicenow.rb, spec/acceptance/reporting/incident_spec.rb, spec/unit/reports/servicenow/event_spec.rb
This change adds report labels to the descriptions of both incidents and
events. The labels help users understand if what changes are represented
in a particular incident or report.
While the incident severity will only reflect the highest severity
change in the report, the labels will reflect all of the different
change types that may have been present in a given report.
=> (PIE-352) Add Report Labels

lib/puppet/reports/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/unit/reports/servicenow/event_spec.rb
When populating the additional information event field I used
additional_information rather additonal_info (the correct name for the
field in the api). I didn't catch it because our mock server had no
issues with additional_info and the tests passed. Testing with a dev
instance revealed the problem.
=> (MAINT) Change additional_information field to additional_info

manifests/event_management.pp
All modules should have proper Puppet Strings documentation. This change
brings the event_management.pp file into compliance.
=> (PIE-362) Document Events Class

provision.yaml, spec/support/acceptance/install_pe.sh
This change switches the install script to look at the more stable
`archives` area of Artifactory for downloading PE. This lays the
groundwork for turning the script into a task that can easily be
parameterizd for PE version and platform version.
In order to do matrix builds with this script it will either have to be
turned into a task with parameters, or edited on the build server before
being executed on the target server.
=> (MAINT) Update PE Install Script

README.md
Moved content from the revised Getting Started Guide back to the README
and added in a development section that closely resembles the CMDB
integration's.
=> (PIE-336) Create README from Getting Started Guide

README.md, files/validate_settings.rb, lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, manifests/event_management.pp, tasks/add_ignore_ok_events_rule.rb
Currently if you include protocol ('https://') in the instance parameter
string you get an error. Added a method to prepend the https if not
already present.
=> (PIE-376) Allow instance parameter to accept protocol

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/event_spec.rb
This change ensures that only facts queried via the $include_facts
parameter. It also switches to adding each fact to the additional_info
field as a top level key to make it easier to target the facts with
event rules.
=> (PIE-378) Send Only Queried Facts

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/shared_examples.rb
Previously when a puppet run resulted in a catalog failure, there were
no report labels populated in the report description.
This change ensures that if a catalog failure occurs there is a report
label is still generated, and additionally the log messages are
included. We include the log messages in the case of catalog failure
because otherwise there is no way to provide the user with feedback
on what might have caused the failure.
=> (PIE-372) Create catalog failure report label

lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb
It's much easier to create rules in servicenow from top level keys in
the additional information field, so this adds the report labels to the
additional info.
=> (PIE-375) Include Report Labels in Additional Info

README.md, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/event_spec.rb
Add a resource_events key to the event additional information field
which contains two additional keys, corrective_changes, and intentional
changes. These keys contain arrays of relevant events. The total
possible set of events is filtered to the same set as already exists in
the description.
=> (PIE-382) Add Resource Events to Additional Info

README.md, files/validate_settings.rb, lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, manifests/event_management.pp, manifests/incident_management.pp, manifests/init.pp, spec/acceptance/reporting/event_spec.rb, spec/acceptance/reporting/incident_spec.rb, spec/acceptance/reporting/misc_spec.rb, spec/support/acceptance/helpers.rb, templates/servicenow_reporting.yaml.epp
Prior to this change, all HTTP requests were done with no SSL
certificate validation.
This change ensures that normal SSL cert validation is done by default,
but users can also turn it off if needed via an opt in parameter.
=> (PIE-394) Enable Certificate Validation

README.md, lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, manifests/event_management.pp, manifests/incident_management.pp, manifests/init.pp, spec/support/unit/reports/servicenow_spec_helpers.rb, templates/servicenow_reporting.yaml.epp
This change adds user parameters to set the HTTP timeout arguments
to the `Net::HTTP.start` method used by the module to make
Servicenow API requests.
The `http_read_timeout` parameter sets the following arguments to the
same value: `ssl_timeout`, `read_timeout`, `connect_timeout`. Most users
will consider these to be functionally the same timeout so there is
little reason at the momen to increase the module's complexity by
exposing each of those arguments as a separate parameter for users.
The `http_write_timeout` parameter sets the `write_timeout` argument.
These parameters are not explicitly acceptance tested because that is
functionally testing the `Net::HTTP` class, which is beyond the scope of
this module. They are unit tested to ensure we don't make any changes
that might …
=> (PIE-383) Add HTTP Timeout Parameters

lib/puppet/util/servicenow.rb
When events and incidents are viewed in a table view in Servicenow, the
the first portion of the description is a static blurb about going to
the console to review the report that generated the table entry.
This change reorders that field so that the first information is the
change type tags. This gives the user at least a slightly helpful
bit of information before clicking into the full entry.
=> (PIE-381) Reorder Description Field

lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/unit/reports/servicenow/event_spec.rb
In the additional information event field the resouce events key is
replaced with 5 keys that categorize resources events in to failures,
corrective changes, etc.
=> (MAINT) Elevate resource event categories to top level keys

README.md, lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, spec/acceptance/reporting/event_spec.rb, spec/unit/reports/servicenow/event_spec.rb
Users need to be able to identify whether an event type is a corrective
or intentional change. This change adds another event type that flags
corrective changes and marks all other changes as intentional.
=> (PIE-380) Add an event type for corrective changes

lib/puppet/util/servicenow.rb
If a user wants to group events by the resource change events,
Servicenow has a bug where it cannot handle the raw resource data that
we add to the additional info field. Some sort of problem is enountered
and the message key for the alert is not changed to the desired value.
This change adds a SHA1 key for each change type to the additional info
field, so that Servicenow can add that field to the message key instead
of the full change data. This fixes event grouping.
=> (PIE-409) Add change type hash keys

tasks/add_ignore_ok_events_rule.rb
Add a check to ensure the targets variable exists and it's safe to call
it before attempting to use it.
=> (MAINT) Fix variable assignment safety

Jenkinsfile, spec/support/acceptance/servicenow/Dockerfile
CI has started to fail because the ruby version in use prior to this
change causes gem dependency conflicts in the Gemfile. Bumping the ruby
version resolves the conflicts.
It is also failing because we have hit the docker cloud rate limit. The
ruby image we use to build the mocking container is been uploaded to
artifactory and we also switch to pulling from artifactory to avoid the
rate limit.
=> (MAINT) Fix CI Errors

manifests/init.pp, spec/classes/init_spec.rb, spec/spec_helper.rb
When a trailing slash is present in the PE_CONSOLE_URL, some customers
have seen bugs.
This change prevents that setting from being written to the settings
yaml file with a trailing slash.
=> (PIE-448) Prevent Trailing Slash in PE Console URL

README.md, Rakefile, lib/puppet/reports/servicenow.rb, manifests/event_management.pp, manifests/incident_management.pp, manifests/init.pp, spec/acceptance/reporting/event_spec.rb, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/event_spec.rb, templates/servicenow_reporting.yaml.epp, types/reportcategories.pp
Re-implemented report filtering from incidents reporting to work for
events reporting. Can choose the type of report being sent by specifying
report categories in init.pp.
Added unit and acceptance tests for the report filter in events reporting.
------
Thanks for your contribution! Note that all community contributors will be required to sign our Contributor License Agreement, unless you fall under the [Trivial Patch Exemption Policy](https://puppet.com/community/trivial-patch-exemption-policy). If you believe it applies to your pull request, please comment explaining why you do not need to sign the CLA. Directions for signing will be attached to your pull request shortly.
Please note that all contributions may be publicly recognized in release notes.
=> (PIE-522) Add Report Filter for Events

lib/puppet/util/servicenow.rb
In util/servicenow.rb, there is a function 'event_security_string' which
needed to be renamed with 'event_severity_string' as it pertains to the
severity of the event and not the security.
=> MAINT Rename Helper function

.fixtures.yml, Gemfile
There are some discrepancies between some of the module versions in use
and the reporting_integration module. This current workaround pins the
versions of the provision module and puppet_litmus that work with the
reporting_integration.
Provision module is set to a specific SHA.
Puppet_litmus is set to version 0.26.0 or earlier (lowerbound of 0.18).
=> PIE-611 Fix Broken Jenkins Tests

README.md, lib/puppet/reports/servicenow.rb, lib/puppet/util/servicenow.rb, manifests/init.pp, spec/support/unit/reports/servicenow_spec_helpers.rb, spec/unit/reports/servicenow/misc_spec.rb, templates/servicenow_reporting.yaml.epp
Created two new parameters 'allow_list' and 'block_list' and a helper
function in util/servicenow.rb that allows users to now specify an
environment other than production.
User can filter on what environment they want to send an event to
ServiceNow by specifying an allow list and block list of environment
names.
Added unit tests for the different list-setting scenarios.
=> PIE-523 Add Environment filter

README.md
This updates the README to include the event filter feature. It briefly
describes the default value of the filter and the other event options
the user can select to filter on.
=> MAINT Update README to include event filter

lib/puppet/reports/servicenow.rb
Added 'cmdb_ci: host,' to lib/puppet/reports/servicenow.rb to include the host fact in the data that gets sent.
=> (PIE-633) Include Hostname

.github/workflows/release.yml, .github/workflows/release_prep.yml, Gemfile, metadata.json
Modify the metadata.json to reflect the new version of the module.
Update the release_prep.yml and release.yml to use new syntax. Instead
of setting the env variables with a : to <<.
=> PIE-651 Publish to Forge Prep

.github/workflows/release.yml, .github/workflows/release_prep.yml, CONTRIBUTING.md
`Release` and `release prep` actions have been updated for consistency
with our other modules. Deprecated user/password Forge authentication
has been replaced with the appropriate token as a Github secret.
CONTRIBUTING.md has been updated for the changes.
=> (PIE-901) Update GitHub deploy actions
